name:                ll-isabelle
version:             0.1.0.0
github:              "githubuser/ll-isabelle"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

description: Add me

dependencies:
- base >= 4.7 && < 5
- bytestring
- llvm-hs
- llvm-hs-pure

library:
  source-dirs: 
  - src
  - src/isabelle_export
  - src/isabelle_modified

executables:
  check-termination-proof:
    main:                Main.hs
    source-dirs:         check_termination_proof
    ghc-options:
    - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
    dependencies:
    - ll-isabelle

  check-lts-represents:
    main:                Main.hs
    source-dirs:         check_lts_represents
    ghc-options:
    - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
    dependencies:
    - ll-isabelle

  run_llvm:
    main:                Main.hs
    source-dirs:         run_llvm
    ghc-options:
    - -threaded
    dependencies:
    - ll-isabelle
